# Generated by Django 4.2.21 on 2025-05-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectionCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("centerId", models.IntegerField()),
                ("name", models.CharField(max_length=20)),
                ("latitue", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.CharField(max_length=100)),
                ("opening_hour", models.CharField(max_length=10)),
                ("closing_hour", models.CharField(max_length=10)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
