# Generated by Django 4.2.21 on 2025-05-08 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectioncenter", old_name="latitue", new_name="latitude",
        ),
    ]
