# Generated by Django 4.2.21 on 2025-05-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_latitue_collectioncenter_latitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("total_collect_amount", models.FloatField(default=0.0)),
                ("total_carbon_reduction", models.FloatField(default=0.0)),
                ("points", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("product_name", models.CharField(max_length=100)),
                ("points_used", models.FloatField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.users"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionHistory",
            fields=[
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="진행중", max_length=20)),
                (
                    "start_latitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "start_longitude",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("distance_walk", models.FloatField(blank=True, null=True)),
                ("collection_amount", models.FloatField(blank=True, null=True)),
                ("carbon_amount", models.FloatField(blank=True, null=True)),
                ("point", models.FloatField(blank=True, null=True)),
                (
                    "center_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.collectioncenter",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.users"
                    ),
                ),
            ],
        ),
    ]
