# Generated by Django 4.2.21 on 2025-05-12 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_users_orderhistory_collectionhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionhistory",
            name="user_id",
            field=models.CharField(max_length=20),
        ),
    ]
