# Generated by Django 4.2.21 on 2025-05-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_collectionhistory_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectioncenter", old_name="centerId", new_name="center_id",
        ),
    ]
