# Generated by Django 4.2.21 on 2025-05-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_centerid_collectioncenter_center_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectionhistory", old_name="center_id", new_name="center",
        ),
    ]
