# Generated by Django 4.2.21 on 2025-05-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_center_id_collectionhistory_center"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectionhistory", old_name="center", new_name="center_id",
        ),
    ]
