# Generated by Django 4.2.21 on 2025-05-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_center_collectionhistory_center_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionhistory",
            name="center_id",
            field=models.CharField(max_length=20),
        ),
    ]
