# Generated by Django 3.2.25 on 2025-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_collectionhistory_center_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectioncenter',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
