# Generated by Django 3.2.25 on 2025-05-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_collectioncenter_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectioncenter',
            name='imageUrl',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
